### ISSUE TITLE
Fix histograms in mala cluster policy 

### ISSUE THREAD

**Issue by constantinpape** [DerThorsten/nifty#110]
The histograms in the mala cluster policy (https://github.com/DerThorsten/nifty/blob/master/include/nifty/graph/agglo/cluster_policies/mala_cluster_policy.hxx) is inaccurate.
To fix this, one might use the nifty histograms (https://github.com/DerThorsten/nifty/blob/master/include/nifty/histogram/histogram.hxx) to fix this.
Pointed out to me by @DerThorsten.

**Comment by DerThorsten** [comment]
should be fixed in dev 13c6deee3803504dc0606616311e15c1caf11510
