### ISSUE TITLE
Src mistake

### ISSUE THREAD

**Issue by Erdos001** [DerThorsten/nifty#26]
when I make the nifty, I have encountered a mistake:
error: ‘const RfImpl’ has no member named ‘predict_proba’
             classifier_.predict_proba(f,p);
I found the error is in the nifty-0.3-beta/include/nifty/graph/gala/gala_classifier_rf.hxx
line 164:
        double predictProbability(const T * features)const{
            // copy stuff atm 
            vigra::MultiArray<2, T>       f(vigra::Shape2(1,numberOfFeatures_));     
            vigra::MultiArray<2, double>  p(vigra::Shape2(1,2));
            for(size_t i=0; i<numberOfFeatures_; ++i){
                f[i] = features[i];
            }
line 164:            **classifier_.predict_proba(f,p);**
            //std::cout<<"predicted p "<<p<<"\n";
            return p(0,1)/numberOfTrees_;
        }
then I found that there is no function named predict_proba in vigra/random_forest_3.hxx
there is only function name predict_probs, then I modified the line to  classifier_.predict_probs(f,p);
 then I compile all the file successfully

**Comment by Erdos001** [comment]
modify the file  nifty-0.3-beta/include/nifty/graph/gala/gala_classifier_rf.hxx at line 164

**Comment by DerThorsten** [comment]
I will update the master soon, also we are happy to take pull requests =)
