### ISSUE TITLE
Adding static properties to the type 'nifty._nifty.Configuration' requires the type to have a custom metaclass.

### ISSUE THREAD

**Issue by BinWang-shu** [DerThorsten/nifty#37]
I compiled the module successfully, but when I ran the test_python.py to examine the module, it raised an error like this:

Traceback (most recent call last):
  File "test_python.py", line 2, in <module>
    import nifty
  File "/home/wangbin/jy/nifty/build/python/nifty/__init__.py", line 3, in <module>
    from _nifty import *
ImportError: Adding static properties to the type 'nifty._nifty.Configuration' requires the type to have a custom metaclass. Please ensure that one is created by supplying the pybind11::metaclass() annotation to the associated class_<>(..) invocation.

I have no idea about this problem. Could you help me to fix the bug?

**Comment by constantinpape** [comment]
Hey,

I just build a  conda package for my fork of nifty, see for details:
https://github.com/constantinpape/nifty/tree/stacked_rag

This branch should have all the functionality, that is available in the master.
Note that this is only available with gurobi right now, but I will upload a version compiled with CPLEX soon.
I will also make a PR to the master soon. w
