### ISSUE TITLE
CGP Examples fail

### ISSUE THREAD

**Issue by constantinpape** [DerThorsten/nifty#60]
The example for using CGP in nifty/scripts/test_cgp2d.py fails with:

  File "test_cgp2d.py", line 37, in <module>
    cellGeometry = ncgp.Geometry2D(tgrid)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. nifty.cgp._cgp.Geometry2D(topologicalGrid: nifty.cgp._cgp.TopologicalGrid2D, fill: bool, sort1Cells: bool)

**Comment by DerThorsten** [comment]
new example 
http://derthorsten.github.io/nifty/docs/python/html/auto_examples/graph/plot_cgp_introduction.html#sphx-glr-auto-examples-graph-plot-cgp-introduction-py
