### ISSUE TITLE
Missing scipy dependency in conda.

### ISSUE THREAD

**Issue by constantinpape** [DerThorsten/nifty#87]
The nifty python gluecode introduces a dependency on scipy and skimage.
Yet, these are not listed in the conda dependencies, which causes the python import of a freshly build package to fail.
@DerThorsten  Is there any reason not to include them as dependencies properly?

**Comment by DerThorsten** [comment]
@constantinpape you are completely righty. Let's do it the right way.
But atm "users"  (aka you) build stuff by hand anyhow? Or is someone using the conda build script atm?

**Comment by DerThorsten** [comment]
https://github.com/DerThorsten/nifty/commit/19962f7abb6b7e858c359166dc1e8de53f0c5763 should fix this. @constantinpape  feel free to have a look at it. I guessed the needed version (took the recent stable ones)

**Comment by DerThorsten** [comment]
I'll close this, feel free to reopen in case this is still making troule

**Comment by constantinpape** [comment]
@DerThorsten, ok this looks fine now.
I have some nifty packages floating around in my conda channel that people who are using the multicut pipeline (Julian and Alex mostly) depend on.
When I tried rebuilding the pipeline conda package today it failed due to the missing nifty dependencies, that's how I noticed.
