### ISSUE TITLE
Segmentation fault in Multicut Example

### ISSUE THREAD

**Issue by janniksgit** [DerThorsten/nifty#98]
Executing `plot_isbi_2012_multicut_2D_simple.py` results in a segmentation fault due to line 349: 
```solver = MulticutObjective.fusionMoveBasedFactory().create(objective)```.
The solver ``MulticutObjective.greedyAdditiveFactory().create(objective)`` works.

**Comment by DerThorsten** [comment]
Should be fixed in dev with https://github.com/DerThorsten/nifty/commit/47cf7fa37dac43bfea92bbe31cfabb8f6c0f8213 .
Should be in master soon
